### ISSUE TITLE
Switching Codebase to V

### ISSUE THREAD

**Issue by loralighte** [fivnex/meml#1]
I have used the V programming language for a little over a year now. I want MEML to be a binary, not an interpreted thing. I was looking into several languages, and so far it seems like V is the perfect option for us. I will be working on translating to V immediately.

**Comment by curlpipe** [comment]
Do you plan to implement this parser by hand?

**Comment by loralighte** [comment]
We do plan to implement the parser by hand. Also, this was completed in [the latest commit](https://github.com/fivnex/meml/commit/143b158f324c5b29086849713e1e774e1d99f8f2)

**Comment by curlpipe** [comment]
V doesn't seem to have any good parser tooling. What library will you be using? It might be a better idea to find a language with a better parser ecosystem.
